In [2]:
import numpy as np

### Practice Problems

Tạo các array sau và in chúng cùng với `.shape`, `.ndim`, `.dtype`:

   * Một array 1 chiều từ 0 đến 9.
   * Một ma trận 3×3 toàn số 7.
   * Một vector có 5 số chia đều từ 0 đến 1.


In [3]:
def pretty_print(a: np.ndarray):
    print(a)
    print("Shape:", a.shape)
    print("Number of dimension:", a.ndim)
    print("Element's data type:", a.dtype)

In [5]:
a = np.arange(10)
pretty_print(a)

[0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Number of dimension: 1
Element's data type: int64


In [7]:
b = np.full((3, 3), 7)
pretty_print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
Shape: (3, 3)
Number of dimension: 2
Element's data type: int64


In [ ]:
c = np.linspace(0, 1, 5)
pretty_print(c)

[0.   0.25 0.5  0.75 1.  ]
Shape: (5,)
Number of dimension: 1
Element's data type: float64
