In [2]:
import numpy as np

### Practice Problems

1. Code: Tạo ma trận 4×4 từ 0 đến 15 (dùng `np.arange`). In ra:

   * Phần tử ở dòng 2, cột 3.
   * Dòng thứ 1 (tất cả cột).
   * Cột cuối cùng.
   * Sub-matrix 2×2 từ góc trên bên trái.

2. Code: Với array `a = np.arange(10)`, hãy:

   * In ra các phần tử chẵn.
   * In ra các phần tử tại index 2, 4, 6, 8.

In [7]:
a = np.array([np.arange(4*i, 4*i+4) for i in range(4)])
print(a[1, 2])
print(a[1])
print(a[:, 3])
print(a[:2, :2])

6
[4 5 6 7]
[ 3  7 11 15]
[[0 1]
 [4 5]]


In [ ]:
a = np.arange(10)
print(a[a % 2 == 0])
print(a[[2, 4, 6, 8]])

[0 2 4 6 8]
[2 4 6 8]
