## 📘 Lesson 2: Tạo và thao tác cơ bản với NumPy arrays

---

### ❓ Today's Question

**"Làm sao để tạo NumPy arrays nhanh chóng, và thao tác cơ bản trên chúng?"**

---

### 💡 Key ideas

* Có nhiều cách tạo **ndarray** ngoài `np.array([...])`:

  * `np.zeros(shape)` → array toàn số 0.
  * `np.ones(shape)` → array toàn số 1.
  * `np.full(shape, value)` → array toàn một giá trị.
  * `np.arange(start, stop, step)` → giống `range` trong Python nhưng trả về ndarray.
  * `np.linspace(start, stop, num)` → chia đều từ start đến stop thành num phần tử.
  * `np.eye(n)` → tạo ma trận đơn vị n×n.

* Các thuộc tính quan trọng của array:

  * `.shape` → kích thước (rows, cols).
  * `.ndim` → số chiều.
  * `.size` → tổng số phần tử.
  * `.dtype` → kiểu dữ liệu.

---

### 📝 Practice Problems

Tạo các array sau và in chúng cùng với `.shape`, `.ndim`, `.dtype`:

   * Một array 1 chiều từ 0 đến 9.
   * Một ma trận 3×3 toàn số 7.
   * Một vector có 5 số chia đều từ 0 đến 1.

---

### 🧩 Solution


In [1]:
import numpy as np

In [2]:
def pretty_print(a: np.ndarray):
    print(a)
    print("Shape:", a.shape)
    print("Number of elements:", a.size)
    print("Number of dimension:", a.ndim)
    print("Element's data type:", a.dtype)

In [3]:
a = np.arange(10)
pretty_print(a)

[0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Number of elements: 10
Number of dimension: 1
Element's data type: int64


In [4]:
b = np.full((3, 3), 7)
pretty_print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
Shape: (3, 3)
Number of elements: 9
Number of dimension: 2
Element's data type: int64


In [5]:
c = np.linspace(0, 1, 5)
pretty_print(c)

[0.   0.25 0.5  0.75 1.  ]
Shape: (5,)
Number of elements: 5
Number of dimension: 1
Element's data type: float64
