## 📘 Lesson 3: Indexing và Slicing trong NumPy

---

### ❓ Today's Question

**"Làm sao để truy cập và cắt (slice) dữ liệu trong NumPy arrays?"**

---

### 💡 Key ideas

* **Indexing (chỉ số)**

  * Giống list Python: `a[0]`, `a[-1]`.
  * 2D array: `a[row, col]`.
  * Có thể dùng slicing trong nhiều chiều: `a[0:2, 1:3]`.

* **Slicing (cắt mảng)**

  * Syntax: `start:stop:step`.
  * Ví dụ: `a[::2]` → lấy cách 2 phần tử.
  * `a[:, 1]` → lấy toàn bộ hàng, cột số 1.

* **Fancy indexing**

  * Dùng list hoặc array để chọn nhiều index cùng lúc:

    * `a[[0, 2, 4]]` → chọn phần tử index 0, 2, 4.
    * `a[:, [1, 3]]` → chọn cột 1 và 3.

* **Boolean indexing**

  * Dùng điều kiện để lọc:

    * `a[a > 5]` → lấy toàn bộ phần tử > 5.

---

### 📝 Practice Problems

1. Tạo ma trận 4×4 từ 0 đến 15 (dùng `np.arange`). In ra:

   * Phần tử ở dòng 2, cột 3.
   * Dòng thứ 1 (tất cả cột).
   * Cột cuối cùng.
   * Sub-matrix 2×2 từ góc trên bên trái.

2. Với array `a = np.arange(10)`, hãy:

   * In ra các phần tử chẵn.
   * In ra các phần tử tại index 2, 4, 6, 8.

---

### 🧩 Solution


In [1]:
import numpy as np

In [2]:
a = np.array([np.arange(4*i, 4*i+4) for i in range(4)])
print(a[1, 2])
print(a[1])
print(a[:, 3])
print(a[:2, :2])

6
[4 5 6 7]
[ 3  7 11 15]
[[0 1]
 [4 5]]


In [3]:
a = np.arange(10)
print(a[a % 2 == 0])
print(a[[2, 4, 6, 8]])

[0 2 4 6 8]
[2 4 6 8]
