## 📘 Lesson 4: Broadcasting trong NumPy

---

### ❓ Today's Question

**"Làm sao NumPy cho phép cộng/trừ/nhân ma trận khác shape mà không cần loop?"**

---

### 💡 Key ideas

* **Broadcasting** = cơ chế NumPy tự động mở rộng chiều để các array **tương thích shape** khi tính toán.

* Quy tắc (Broadcasting rules):

  1. So sánh shape của 2 array từ phải sang trái.
  2. Nếu cùng chiều → ok.
  3. Nếu một chiều = 1 → được “kéo dãn” thành chiều kia.
  4. Nếu khác nhau mà không có 1 → ❌ báo lỗi.

* Ví dụ:

  * `(3, )` + `(3, )` → ok, element-wise.
  * `(3, 1)` + `(1, 4)` → kết quả `(3, 4)`.
  * `(2, 3)` + `(3, )` → kết quả `(2, 3)` (vector broadcast).

* Broadcasting giúp code **ngắn gọn, chạy nhanh** thay vì loop.

---

### 📝 Practice Problems

1. Tạo `a = np.array([[1,2,3],[4,5,6]])` (shape (2,3)).

   * Cộng với vector `b = np.array([10,20,30])`.
   * Cộng với cột `c = np.array([[100],[200]])`.
     In kết quả và shape.

2. Giả sử `x = np.ones((3,1))` và `y = np.arange(3)`.

   * In ra `x + y` và shape. Giải thích tại sao broadcasting xảy ra.

---

### 🧩 Solution


In [1]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c = np.array([[100],[200]])

In [ ]:
print(d:=a+b+c)
print(d.shape)

[[111 122 133]
 [214 225 236]]
(2, 3)


In [6]:
x = np.ones((3, 1))  # shape: (3, 1)
y = np.arange(3)     # shape: (3,)
print(z:=x+y)        # shape: (3, 3)
print(z.shape)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
(3, 3)
